apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: backend-tests-dotnet-basic-lffeoogw
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/tsscui/backend-tests-dotnet-basic-lffeoogw:azure-8b0eb1e10c28a1ae445c2733ef6fae91b34a94c9
        name: container-image  
